name: Build Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_ttf
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
    - name: Build
      shell: msys2 {0}
      run: |
        mkdir -p build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_MAKE_PROGRAM=mingw32-make
        mingw32-make
    - name: Package
      shell: msys2 {0}
      run: |
        mkdir -p releases/windows
        cp build/hanoi.exe releases/windows/
        # Copy required DLLs from MSYS2
        which SDL2.dll | xargs cp -t releases/windows/
        which SDL2_ttf.dll | xargs cp -t releases/windows/
        which libfreetype-6.dll | xargs cp -t releases/windows/
        which zlib1.dll | xargs cp -t releases/windows/
        # Create zip file
        cd releases/windows
        powershell Compress-Archive -Path * -DestinationPath ../../TowersOfHanoi-windows.zip -Force
    - uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: TowersOfHanoi-windows.zip

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make cmake libsdl2-dev libsdl2-ttf-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. 
        cmake --build . 
    - name: Package
      run: |
        mkdir -p releases/linux
        cp build/hanoi releases/linux/
        chmod +x releases/linux/hanoi
        cd releases/linux
        tar czf ../../TowersOfHanoi-linux.tar.gz *
    - uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: TowersOfHanoi-linux.tar.gz

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-build/TowersOfHanoi-windows.zip
          linux-build/TowersOfHanoi-linux.tar.gz
